### ISSUE TITLE
Remove RAILS install path from stack traces in task logs

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#1129]
Task logs sometimes contain stack traces (there is even a helper method to add them to it). E.g

```
[2021-06-09 10:08:40 EDT] /home/prioux/CBRAIN/Bourreau/lib/scir_slurm.rb:162:in `qsubout_to_jid'
[2021-06-09 10:08:40 EDT] /home/prioux/CBRAIN/Bourreau/lib/scir.rb:137:in `run'
[2021-06-09 10:08:40 EDT] /home/prioux/CBRAIN/Bourreau/app/models/cluster_task.rb:1970:in `submit_cluster_job'
[2021-06-09 10:08:40 EDT] /home/prioux/CBRAIN/Bourreau/app/models/cluster_task.rb:745:in `block (2 levels) in setup_and_submit_job'
[2021-06-09 10:08:40 EDT] /home/prioux/CBRAIN/Bourreau/app/models/cluster_task.rb:740:in `chdir'
```

Remove the constant prefix that represents the parent of the RAILS installation (e.g. `/home/prioux/CBRAIN` in the example above).

**Comment by prioux** [comment]
Done in dev directly, in 5d69f5ff0
