### ISSUE TITLE
An error message when starting console without intalling pluging

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#1445]
I am getting hirb error on the console start (both master and dev) after disabling plugins. Console works fine though (save  BACs attribute_names and friends). Maybe then raise warning rather than error?
```
CBRAIN Rails Console Initialization starting
Current user is now: admin

Current project is now: (nil)

load error: /home/users/sboroday/cbrain/BrainPortal/config/console_rc/init_rc.rb

NoMethodError: undefined method `attribute_names' for BackgroundActivity:Class

Did you mean?  attr_internal

	/home/users/sboroday/cbrain/BrainPortal/config/console_rc/lib/wirble_hirb_looksee.rb:80:in `block in <top (required)>'

	/home/users/sboroday/cbrain/BrainPortal/config/console_rc/lib/wirble_hirb_looksee.rb:76:in `each'

	/home/users/sboroday/cbrain/BrainPortal/config/console_rc/lib/wirble_hirb_looksee.rb:76:in `<top (required)>'

	/home/users/sboroday/.rvmpath/ruby/2.7.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
```

to reproduce run

```
cd ~/cbrain/BrainPortal  # or other place of CBRAIN installation
rake cbrain:plugins:clean:all
rails console
```

**Comment by MontrealSergiy** [comment]
that helps.  BackgroundActivity is more of intrinsic feature than a plugin, so one would expect it to work without plugin install.

**Comment by prioux** [comment]
Some of the core functionality is provided as internal plugins. So running the script to install plugins is `required` at all times, even on a bare system that has no external plugins.
