### ISSUE TITLE
Installing bourreau - `cannot load such file site_ruby/2.2.0/sys/proctable/cgroup_entry`

### ISSUE THREAD

**Issue by juanprietob** [aces/cbrain#265]
Do I need to have a specific version of ruby?

```
$ bundle show sys-proctable
~/.rvm/gems/ext-ruby-2.2.3-p173/bundler/gems/sys-proctable-0aae87117674

$ cd ~/.rvm/gems/ext-ruby-2.2.3-p173/bundler/gems/sys-proctable-0aae87117674

$ rake install

cp lib/linux/sys/proctable.rb~/install/lib/ruby/site_ruby/2.2.0/sys`

cd cbrain/Bourreau
$ rake cbrain:plugins:install:plugins

rake aborted!
LoadError: cannot load such file -- ~/install/lib/ruby/site_ruby/2.2.0/sys/proctable/cgroup_entry
~/.rvm/gems/ext-ruby-2.2.3-p173/bundler/gems/sys-proctable-0aae87117674/lib/sys-proctable.rb:1:in `require'
~/.rvm/gems/ext-ruby-2.2.3-p173/bundler/gems/sys-proctable-0aae87117674/lib/sys-proctable.rb:1:in `<top (required)>'
~/.rvm/gems/ext-ruby-2.2.3-p173/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
~/.rvm/gems/ext-ruby-2.2.3-p173/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
~/.rvm/gems/ext-ruby-2.2.3-p173/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
~/.rvm/gems/ext-ruby-2.2.3-p173/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
~/.rvm/gems/ext-ruby-2.2.3-p173/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
~/.rvm/gems/ext-ruby-2.2.3-p173/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
~/.rvm/gems/ext-ruby-2.2.3-p173/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
~/source/cbrain/Bourreau/config/application.rb:29:in `<top (required)>'
~/source/cbrain/Bourreau/Rakefile:4:in `require'
~/source/cbrain/Bourreau/Rakefile:4:in `<top (required)>'
~/.rvm/gems/ext-ruby-2.2.3-p173/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ext-ruby-2.2.3-p173/bin/ruby_executable_hooks:15:in `<main>'`
```

**Comment by prioux** [comment]
Hi Juan Carlos,

That's an interesting error, I've never seen this before. Normally the
installation of sys-proctable is rather straightforward, aside from that
special step. You're doing everything correctly. Let me investigate a little...

Pierre

**Comment by prioux** [comment]
Can you give me the output of the command "rvm info" (you can censor parts of it if you think it contains confidential or sensitive information). I suspect that sys-proctable doesn't work well if installed as a gem while Ruby itself isn't.

**Comment by prioux** [comment]
I took the liberty of reformating your comment a little. Just so you know.

**Comment by juanprietob** [comment]
This is the output of `$rvm info`

``` bash
ext-ruby-2.2.3-p173:

  system:
    uname:       "Linux 2.6.18-238.12.1.el5 #1 SMP Sat May 7 20:18:50 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux"
    system:      "redhat/5/x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)"
    zsh:         "/bin/zsh => zsh 4.2.6 (x86_64-redhat-linux-gnu)"

  rvm:
    version:      "rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "5 hours 42 minutes 2 seconds ago"
    path:         "~/.rvm"

  ruby:
    interpreter:  "ruby"
    version:      "2.2.3p173"
    date:         "2015-08-18"
    platform:     "x86_64-linux"
    patchlevel:   "2015-08-18 revision 51636"
    full_version: "ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]"

  homes:
    gem:          "~/.rvm/gems/ext-ruby-2.2.3-p173"
    ruby:         "~/.rvm/rubies/ext-ruby-2.2.3-p173"

  binaries:
    ruby:         "~/.rvm/rubies/ext-ruby-2.2.3-p173/bin/ruby"
    irb:          "~/.rvm/rubies/ext-ruby-2.2.3-p173/bin/irb"
    gem:          "~/.rvm/rubies/ext-ruby-2.2.3-p173/bin/gem"
    rake:         "~/.rvm/rubies/ext-ruby-2.2.3-p173/bin/rake"

  environment:
    PATH:         "~/.rvm/gems/ext-ruby-2.2.3-p173/bin:~/.rvm/gems/ext-ruby-2.2.3-p173@global/bin:~/.rvm/rubies/ext-ruby-2.2.3-p173/bin:/nas02/apps/cmake-2.8.12.2/bin:/nas02/apps/git-1.8.5.3/bin:/opt/lsf/9.1/linux2.6-glibc2.3-x86_64/etc:/opt/lsf/9.1/linux2.6-glibc2.3-x86_64/bin:/opt/kusu/bin:/opt/kusu/sbin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/opt/lsf/scripts:/opt/dell/srvadmin/bin:~/source/install/bin:~/source/cmake/bin:~/.rvm/bin:~/bin"
    GEM_HOME:     "~/.rvm/gems/ext-ruby-2.2.3-p173"
    GEM_PATH:     "~/.rvm/gems/ext-ruby-2.2.3-p173:~/.rvm/gems/ext-ruby-2.2.3-p173@global"
    MY_RUBY_HOME: "~/.rvm/rubies/ext-ruby-2.2.3-p173"
    IRBRC:        "~/.rvm/rubies/ext-ruby-2.2.3-p173/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by prioux** [comment]
Thanks; unfortunately I don't see anything wrong in there.

I search several of my CBRAIN installations, I can't find anywhere a file or directory named "cgroup_entry"...

I suspect more and more than sys-proctable has changed; our Gemfile specifies to 'use the latest', and that doesn't work anymore for some reason. I'm looking further now.

**Comment by prioux** [comment]
Ah yes. It works with sys-proctable 0.9.8, but the most recent version is 0.9.9 (which contains that mysterious `cgroup_entry` file).

Can you try this? Edit the "Gemfile" and change this:

```
gem "sys-proctable", :git => 'git://github.com/djberg96/sys-proctable.git'
```

to this:

```
gem "sys-proctable", :git => 'git://github.com/djberg96/sys-proctable.git', :ref => "ac047b6"
```

the run `bundle install` again.

**Comment by prioux** [comment]
Note to CBRAIN devs: we need to fix the way sys-proctable is loaded into CBRAIN (or at least request 0.9.8 explicitely)

**Comment by natacha-beck** [comment]
Same kind of issue with the mysql2 gem:

The solution is to modify the Gemfile to use:
> gem "mysql2", "<0.4"
(it installs mysql2 version 0.3.20).


2015-12-03 16:10 GMT-05:00 Pierre Rioux <notifications@github.com>:

**Comment by juanprietob** [comment]
That did it!
