### ISSUE TITLE
In user file view, "Download  File" button crashes with  "Couldn't find Userfile with id=download" error

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#311]
Full trace:

```
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activerecord/lib/active_record/relation/finder_methods.rb:344:in `find_one'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activerecord/lib/active_record/relation/finder_methods.rb:315:in `find_with_ids'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activerecord/lib/active_record/relation/finder_methods.rb:107:in `find'
app/models/userfile.rb:339:in `find_accessible_by_user'
app/controllers/userfiles_controller.rb:290:in `show'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/abstract_controller/base.rb:167:in `process_action'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/callbacks.rb:525:in `block in _run__2226815674746059455__process_action__2123525060749793347__callbacks'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_948'
app/controllers/application_controller.rb:101:in `activate_user_time_zone'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_948'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/callbacks.rb:513:in `_run__2226815674746059455__process_action__2123525060749793347__callbacks'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/abstract_controller/callbacks.rb:17:in `process_action'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/notifications.rb:123:in `block in instrument'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/notifications.rb:123:in `instrument'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activerecord/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/abstract_controller/base.rb:121:in `process'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/abstract_controller/rendering.rb:45:in `process'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_controller/metal.rb:203:in `dispatch'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_controller/metal.rb:246:in `block in action'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/routing/route_set.rb:73:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/routing/route_set.rb:608:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.7) lib/rack/etag.rb:23:in `call'
rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/head.rb:14:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activerecord/lib/active_record/query_cache.rb:64:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/callbacks.rb:405:in `_run__4229444993978263647__call__2062213166809947372__callbacks'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/reloader.rb:65:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/railties/lib/rails/rack/logger.rb:32:in `call_app'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/railties/lib/rails/rack/logger.rb:16:in `block in call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/tagged_logging.rb:22:in `tagged'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/railties/lib/rails/rack/logger.rb:16:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.7) lib/rack/runtime.rb:17:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/activesupport/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.7) lib/rack/lock.rb:15:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/actionpack/lib/action_dispatch/middleware/static.rb:83:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/railties/lib/rails/engine.rb:484:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/railties/lib/rails/application.rb:231:in `call'
rack (1.4.7) lib/rack/content_length.rb:14:in `call'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/railties/lib/rails/rack/log_tailer.rb:17:in `call'
thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.3) lib/thin/connection.rb:84:in `catch'
thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.3) lib/thin/connection.rb:53:in `process'
thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.8) lib/eventmachine.rb:193:in `run_machine'
eventmachine (1.0.8) lib/eventmachine.rb:193:in `run'
thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
thin (1.6.3) lib/thin/server.rb:162:in `start'
rack (1.4.7) lib/rack/handler/thin.rb:13:in `run'
rack (1.4.7) lib/rack/server.rb:268:in `start'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/railties/lib/rails/commands/server.rb:70:in `start'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/railties/lib/rails/commands.rb:55:in `block in <top (required)>'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/railties/lib/rails/commands.rb:50:in `tap'
/home/cbrain/.rvm/gems/ruby-2.2.0/bundler/gems/rails-d94d77c55c59/railties/lib/rails/commands.rb:50:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
```

**Comment by prioux** [comment]
I've edited your bug report Tristan to properly blockquote your trace, it was unreadable otherwise. Please use the GitHub markup conventions when quoting code or traces.
