### ISSUE TITLE
BourreauSubWorkers can crash if task deleted while processing

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#430]
A rare situation is a task object is deleted while a subworker was about to start working on it.

This makes the SubWorker crash with an exception, which causes the parent Worker to exit (because that is not allowed).

Detect this and recover gracefully by ignoring the task: it will not reappear at the next check cycle anyway.

From the BourreauWorkers log file:

```
2016-07-18 21:51:57 FATAL SubWorker-30245: Exception processing task BrainStorm/337206: ActiveRecord::RecordNotFound Couldn't find CbrainTask::Dcm2mnc with id=337206 [WHERE `cbrain_tasks`.`type` IN ('CbrainTask::Dcm2mnc')]
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/relation/finder_methods.rb:344:in `find_one'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/relation/finder_methods.rb:315:in `find_with_ids'
/home/cbrainsys/.rvm/gems/ruby-2.2.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/relation/finder_methods.rb:107:in `find'
```

**Comment by prioux** [comment]
Fixed by #456
