### ISSUE TITLE
Userfile pagination crash when given a string such as "1--"

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#438]
I entered "1--" in the userfile index's "per page" input box and it raised an exception. It probably happens in other pages too.

```
Process Name: Rails Server BrainPortal CBRAIN 3026
Params: {"_pag_scope_name"=>"userfiles", "page"=>"1", "per_page"=>"1--", "_"=>"1469536296669", "action"=>"index", "controller"=>"userfiles"}
Exception: TypeError: nil can't be coerced into Fixnum

/home/cbrainsys/CBRAIN/BrainPortal/app/controllers/userfiles_controller.rb:88:in `*'
/home/cbrainsys/CBRAIN/BrainPortal/app/controllers/userfiles_controller.rb:88:in `index'
```

**Comment by prioux** [comment]
Directly committed to `dev` branch.
