### ISSUE TITLE
Plugin installation in Bourreau

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#539]
The plugin installation rake task fails as follows:

```
rake cbrain:plugins:install:all
[...]
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/glatard/code/cbrain/Bourreau/config/database.yml
/home/glatard/.rvm/gems/ruby-2.2.4/bundler/gems/rails-e4b0a5f66ebd/railties/lib/rails/application/configuration.rb:115:in `read'
/home/glatard/.rvm/gems/ruby-2.2.4/bundler/gems/rails-e4b0a5f66ebd/railties/lib/rails/application/configuration.rb:115:in `database_configuration'
/home/glatard/.rvm/gems/ruby-2.2.4/bundler/gems/rails-e4b0a5f66ebd/activerecord/lib/active_record/railtie.rb:84:in `block (2 levels) in <class:Railtie>'
/home/glatard/.rvm/gems/ruby-2.2.4/bundler/gems/rails-e4b0a5f66ebd/activesupport/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
/home/glatard/.rvm/gems/ruby-2.2.4/bundler/gems/rails-e4b0a5f66ebd/activesupport/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'

```
The workaround is to copy `config/database.yml` from the portal, which has to be done every time the Bourreau starts since this file is deleted when the Bourreau starts.

The rake task then fails with the following error:
```
Errno::ENOENT: No such file or directory @ dir_chdir - /home/glatard/code/cbrain/Bourreau/public/cbrain_plugins/userfiles
```
Creating the directories works but then the error is:
```
Errno::ENOENT: No such file or directory @ dir_chdir - /home/glatard/code/cbrain/Bourreau/public/cbrain_plugins/cbrain_tasks
```
and these directories have to be created as well.

**Comment by prioux** [comment]
Like the instructions say for the plugins package installation (see for neuro at https://github.com/aces/cbrain-plugins-neuro ), you're not supposed to run

```
rake cbrain:plugins:install:all
```

but instead

```
rake cbrain:plugins:install:plugins
```

on the BrainPortal app side (even if you're installing a Bourreau)
