### ISSUE TITLE
Bourreau Workers can die if a task object is destroyed while active

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#749]
Not a big problem, but it woudl be nice if a worker could just handle the case of a disappearing task object.

```
2018-07-04 11:56:13 FATAL SubWorker-94426: Some object has disappeared while processing task 'Cedar/566697': ActiveRecord::RecordNotFound Couldn't find CbrainTask::Civet with 'id'=566697 [WHERE `cbrain_tasks`.`type` IN ('CbrainTask::Civet')]
/home/prioux/.rvm/gems/ruby-2.4.1@cbrain/gems/activerecord-5.0.6/lib/active_record/relation/finder_methods.rb:353:in `raise_record_not_found_exception!'
/home/prioux/.rvm/gems/ruby-2.4.1@cbrain/gems/activerecord-5.0.6/lib/active_record/relation/finder_methods.rb:479:in `find_one'
/home/prioux/.rvm/gems/ruby-2.4.1@cbrain/gems/activerecord-5.0.6/lib/active_record/relation/finder_methods.rb:458:in `find_with_ids'
/home/prioux/.rvm/gems/ruby-2.4.1@cbrain/gems/activerecord-5.0.6/lib/active_record/relation/finder_methods.rb:66:in `find'
/home/prioux/.rvm/gems/ruby-2.4.1@cbrain/gems/activerecord-5.0.6/lib/active_record/querying.rb:3:in `find'
/home/prioux/.rvm/gems/ruby-2.4.1@cbrain/gems/activerecord-5.0.6/lib/active_record/core.rb:151:in `find'
/home/prioux/.rvm/gems/ruby-2.4.1@cbrain/gems/activerecord-5.0.6/lib/active_record/persistence.rb:448:in `block in reload'
/home/prioux/.rvm/gems/ruby-2.4.1@cbrain/gems/activerecord-5.0.6/lib/active_record/scoping/default.rb:35:in `block in unscoped'
/home/prioux/.rvm/gems/ruby-2.4.1@cbrain/gems/activerecord-5.0.6/lib/active_record/relation.rb:351:in `scoping'
/home/prioux/.rvm/gems/ruby-2.4.1@cbrain/gems/activerecord-5.0.6/lib/active_record/scoping/default.rb:35:in `unscoped'
/home/prioux/CBRAIN/Bourreau/lib/cbrain_extensions/active_record_extensions/single_table_inheritance.rb:47:in `unscoped'
```

Unfortunately the logs only show 10 lines of stack trace so we don't know where in the Worker code this happens.

**Comment by prioux** [comment]
By the way, it's in the SubWorker code.
