### ISSUE TITLE
(Dev branch) Links to ExceptionLog objects don't work anymore

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#750]
Clicking on an exception in the exception log index page results in a routing error:

```
ActionView::Template::Error: No route matches {:action=>"update", :controller=>"exception_logs", :id=>1737} in exception_logs/show
```

Trace (excerpt, edited)

```
.rvm/gems/ruby-2.4.1@cbrain/gems/actionview-5.0.6/lib/action_view/routing_url_for.rb:90:in `url_for'
BrainPortal/app/helpers/show_table_helper.rb:334:in `show_table'
BrainPortal/app/views/exception_logs/show.html.erb:39:in `_app_views_exception_logs_show_html_erb___1668846558194399177_63116780'
```

**Comment by prioux** [comment]
This is likely related to (or caused by) #744
