### ISSUE TITLE
Killing a subprocess (worker, subworker) no longer works

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#92]
Something new in Rails (or Ruby) prevents handling properly signals TERM, which are often used internally by Bourreau Workers and the SshAgentLocker. Instead of triggering the signal handler, the entire ruby process crash.

This is terrible because TERM, when received by a BourreauWorker, is supposed to be
propagated to any SubWorkers currently operating. Now the BourreauWorker exits, but the SubWorker
continue to operate.

E.g trace for the SshAgentLocker:

```
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: Exception raised: ThreadError : can't be called from trap context
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: /home/cbrainsys/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:185:in `lock'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: /home/cbrainsys/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:185:in `mon_enter'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: /home/cbrainsys/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:209:in `mon_synchro
nize'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: /home/cbrainsys/.rvm/gems/ruby-2.2.0/gems/log4r-1.1.10/lib/log4r/outputter/outputter
.rb:130:in `synch'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: /home/cbrainsys/.rvm/gems/ruby-2.2.0/gems/log4r-1.1.10/lib/log4r/outputter/outputter
.rb:110:in `canonical_log'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: (eval):3:in `info'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: (eval):8:in `block in info'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: (eval):8:in `each'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: (eval):8:in `info'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: /home/cbrainsys/CBRAIN/BrainPortal/app/models/worker.rb:701:in `info'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: /home/cbrainsys/CBRAIN/BrainPortal/app/models/worker.rb:249:in `block (2 levels) in 
start'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: /home/cbrainsys/CBRAIN/BrainPortal/app/models/worker.rb:469:in `call'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: /home/cbrainsys/CBRAIN/BrainPortal/app/models/worker.rb:469:in `sleep'
2015-05-19 18:36:03 FATAL PortalAgentLocker-31519: /home/cbrainsys/CBRAIN/BrainPortal/app/models/worker.rb:469:in `wait_for_requested_i
nterval'
```

**Comment by remibernard** [comment]
This seems to be caused by log4r trying to acquire a lock (`/home/cbrainsys/.rvm/gems/ruby-2.2.0/gems/log4r-1.1.10/lib/log4r/outputter/outputter
.rb:130:in 'synch'`) in a signal handler (BrainPortal/app/models/worker.rb:701), which is no longer allowed as of Ruby 2.0.0:

> Mutex
>    incompatible changes:
>        Mutex#lock, Mutex#unlock, Mutex#try_lock, Mutex#synchronize and Mutex#sleep
>        are no longer allowed to be used from trap handler and raise a ThreadError in such case.
>        Mutex#sleep may spurious wakeup. Check after wakeup.

http://docs.ruby-lang.org/en/2.1.0/NEWS-2_0_0.html

Maybe the lock could be disabled for this operation?

**Comment by prioux** [comment]
Funny, I just reassigned this issue to you, and I see you already started investigating.

Keep investigating, don't commit code until we talk. Propose solution if possible.

**Comment by remibernard** [comment]
As far as I can see, there is no supported way to avoid log4r's lock. The stack trace tells us `canonical_log` ([outputter.rb:109](https://github.com/colbygk/log4r/blob/40e2c2edd657a21b34f09dec7de238f348b6f428/lib/log4r/outputter/outputter.rb#L109)) is called to perform output:
```ruby
# This method handles all log events passed to a typical Outputter. 
# Overload this to change the overall behavior of an outputter. Make
# sure that the new behavior is thread safe.

def canonical_log(logevent)
  synch { write(format(logevent)) }
end
```

`synch` is defined as: ([outputter.rb:130](https://github.com/colbygk/log4r/blob/40e2c2edd657a21b34f09dec7de238f348b6f428/lib/log4r/outputter/outputter.rb#L130)):
```ruby
def synch; synchronize { yield } end
```

Of those methods, only `write` is redefined in a subclass, as the hierarchy is `FileOutputter < IOOutputter < Outputter`.

**Comment by remibernard** [comment]
A (somewhat) clean and simple solution would be to delay logging to outside the signal handler:
```ruby
# ...
Signal.trap("TERM") do
  self.pending_log << "Got SIGTERM, scheduling stop"
  self.handle_stop_reception
end

# ...
self.pending_log.each { |line| self.worker_log.info line }
```

Aside from monkeypatching log4r or Monitor functions, another solution could be to wrap `worker_log` for a special path if executed within a signal handler.
